### ISSUE TITLE
values.h

### ISSUE THREAD

**Issue by gitferry** [aesuli/mp-boost#1]
Appreciate for your work.

But when I compile the source code, it can't find the file 'values.h'.

Here's the detail.

In file included from boostingmodel.cpp:12:
./mpboostmodel.h:16:10: fatal error: 'values.h' file not found
# include <values.h>

```
     ^
```

1 error generated.
make: **\* [boostingmodel.o] Error 1

**Comment by aesuli** [comment]
The issue you see is similar to this one: http://macosx.forked.net/bbarchive/forum1/000063.html
I have removed the use of values.h, replacing it with limits (fixing the code where needed).
It continues working on my machine and now it should work also on your.
